### ISSUE TITLE
[BE] Chat/Game : Test를 하기 위해 Tester 전용 JWT 발급 기능

### ISSUE THREAD

**Issue by Moongss** [Architects8080/backend#19]
## 구현할 기능

* Test를 위해 42Oauth를 거치지 않고 middleware에서 cookie값 확인 후 특정 값과 매칭되면 JWT 발급.

## 공유 사항

* game쪽에서 간단히 테스트 한다고 만든거긴 한데,, Chat에도 유용하게 쓰일까요?
* 사용방법/흐름은 정리되는대로 아래에 업로드하겠습니다.

**Comment by hysimok** [comment]
아 PR을 먼저 보고 이슈를 봤네요 ㅎㅎ
이 이슈는 #12 에서 공유사항에 있던 내용 결정한 거 맞죠?

**Comment by Moongss** [comment]
> 아 PR을 먼저 보고 이슈를 봤네요 ㅎㅎ
> 이 이슈는 #12 에서 공유사항에 있던 내용 결정한 거 맞죠?
> chat 에서도 물론 유용하게 쓰일 것 같습니다.

넵 맞습니다!
