### ISSUE TITLE
[BE] Game :  socket-user.service.ts를 socket 폴더 내부로 이동

### ISSUE THREAD

**Issue by Moongss** [Architects8080/backend#32]
## 구현할 기능

* 이동하신 뒤, 브랜치 따로 파서 PR 날려주세요.

## 공유 사항
* 빨리 할 수록 Chat팀이 편해질 것 같습니다.

**Comment by skdlsco** [comment]
### scope 관련 공유 사항입니다.
scope.DEFAULT의 경우 (공식문서에 singleton 이라고 나와있습니다.)
TestService사용한다 가정하고 
- Service 사용할 때 해당 Module에서 `providers:[TestService]` 한 경우 
언제나 새 Instance가 생성됩니다.

- `imports`한 모듈에서 `exports`된 Service를 사용하는 경우
`imports` 모듈에서의 `Instance`를 **공유**하여 사용하게 됩니다.
- 같은 Service를 exports하는 Module를 두개 이상 imports했을 때 맨 마지막에 import한 Module의 Service를 사용하게 됩니다.
---
```
@Module({
  controllers: [AController],
  providers: [TestService],
  exports: [TestService],
})
export class AModule{}

@Module({
  imports: [AModule],
  controllers: [BController],
})
export class BModule{}
```
위 같은 경우는 `BModule`이 `AModule`에서 만든 `TestService`를 사용하게 됩니다.

 ---
```
@Module({
  controllers: [AController],
  providers: [TestService],
  exports: [TestService],
})
export class AModule{}

@Module({
  imports: [AModule],
  controllers: [BController],
  providers: [TestService],
  exports: [TestService]
})
export class BModule{}
```
위와 같은 경우에는 `BModule`에서 providers를 통해 `TestService`를 새로 만들었기 때문에 `AModule, BModule` 각각 `TestService`를 갖게 됩니다.

 ---
```
@Module({
  imports: [AModule, BModule],
  controllers: [CController],
})
export class CModule {}
```
위 같은 경우 `AModule`과 `BModule`에서 각각 `TestService Instance`를 갖고 있기 때문에 마지막에 `import`된 `BModule`의 `TestService`를 사용하게 됩니다.
이런 경우 BModule과 AModule에서의 TestService를 구분하고 싶을 때 아래 예시 처럼 사용하면 해결할 수 있습니다.
``` 
b.test-service.ts
export const BTestService = {
  provide: "B_SERVICE",
  useClass: TestService,
  scope: Scope.DEFAULT
}

b.controller.ts
@Controller('b')
export class BController {
  constructor(
    @Inject("B_SERVICE")
    private testService: TestService) {}
}

b.module.ts
@Module({
  imports: [AModule],
  controllers: [BController],
  providers: [BTestService],
  exports: [BTestService]
})
export class BModule{}
```
