### ISSUE TITLE
[BE] Custom SocketAdapter 구현

### ISSUE THREAD

**Issue by skdlsco** [Architects8080/backend#9]
## 구현할 기능
cors를 넣어주는 CustomSocketAdapter 구현

## 공유 사항
```
@WebSocketGateway(4000, { cors: { origin: 'http://localhost:3000', credentials: true }, namespace: 'socket'})
```
위처럼 WebSocketGateway를 사용할 때 cors 처리를 위해 client주소를 decorator안에 넣어줘야 합니다. 
client 주소를 configService를 통해 가져올 수 있게 CustomSocketAdapter 만드려고 합니다

**Comment by skdlsco** [comment]
`src/socket/`에 넣어도 괜찮을까요

**Comment by Moongss** [comment]
chat/game에 공통적으로 쓰이는 부분인 것 같은데, src/socket에 넣어도 괜찮아 보입니다.

**Comment by sjeong12** [comment]
`this.configService.get<string>('client_address')` 이 방식으로 불러오는 것과 어떤 차이가 있나요?

**Comment by skdlsco** [comment]
WebSocketGateway가 decorator여서 직접 불러오는게 불가능 해요 그래서 따로 adapter를 상속받아서 service에서 불러올 수 있게 하는 거에요!

**Comment by Moongss** [comment]
comment 알림 test입니다.

**Comment by sjeong12** [comment]
말씀하신 것처럼 채팅에서도 websocket을 쓰기때문에 `src/socket`경로가 괜찮을 것 같습니다
