### ISSUE TITLE
[BE] notification: 알림 모듈 entity, gateway 생성

### ISSUE THREAD

**Issue by sjeong12** [Architects8080/backend#93]
## 구현할 기능
notification 모듈과 entity, gateway를 생성합니다

![image](https://user-images.githubusercontent.com/45448572/137262519-a254ff06-b492-4926-a3bd-b605b7043bdf.png)

Figma를 참고하여, `title`, `userId`, `friendId` 3가지를 복합키로 사용할 계획입니다
- `title` : notification 유형(친구 신청, 게임 초대 등)
- `userId` : 알림을 전송한 유저
- `friendId` : 알림을 수신한 유저

3가지를 복합키로 사용하므로, **A**(userId) -> **B**(friendId)에게 **친구 신청**(title)을 중복으로 보낼 수 없습니다
![image](https://user-images.githubusercontent.com/45448572/137262575-274e6202-5091-4bec-b487-d0b083611d68.png)

## 공유 사항
게임 초대의 경우 이미 초대 메시지를 보냈더라도, 또 다른 방을 생성하면 다시 초대가 가능해야하는데, 어떤 방법이 좋을까요?
- 기존에 있던 초대메시지를 삭제하고 새 메시지를 추가
- title에 방이름을 명시하여 서로 다른 요청으로 구분 -> 이전 초대 메시지와 새로운 초대 메시지가 모두 notification에 남게 됨

**Comment by skdlsco** [comment]
notification 자신이 id를 따로 갖으면 될 것 같아요

**Comment by sjeong12** [comment]
id를 따로 추가하고, 중복은 따로 확인하는 과정을 추가하는게 좋을까요?
